-- Create enquiries table to store customer booking inquiries
CREATE TABLE IF NOT EXISTS enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR NOT NULL,
  email VARCHAR,
  phone_number VARCHAR NOT NULL,
  service_interested VARCHAR NOT NULL,
  travel_date DATE,
  number_of_days INTEGER,
  preferred_vehicle_type VARCHAR, -- Store vehicle type selection
  message TEXT,
  status VARCHAR DEFAULT 'new', -- 'new', 'contacted', 'closed', 'booked'
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Disable Row-Level Security to allow direct anonymous API writes
ALTER TABLE enquiries DISABLE ROW LEVEL SECURITY;
