-- 1. Modify billdata table to support payment status tracking
ALTER TABLE billdata ADD COLUMN IF NOT EXISTS payment_status VARCHAR DEFAULT 'Not Received';
ALTER TABLE billdata ADD COLUMN IF NOT EXISTS payment_mode VARCHAR DEFAULT NULL;
ALTER TABLE billdata ADD COLUMN IF NOT EXISTS payment_comment TEXT DEFAULT NULL;

-- 2. Create payment acknowledgement requests table
CREATE TABLE IF NOT EXISTS payment_acknowledgement_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no BIGINT NOT NULL,
  payment_mode VARCHAR NOT NULL,
  comment TEXT,
  status VARCHAR DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  requested_by VARCHAR DEFAULT 'staff',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Create expense reports table
CREATE TABLE IF NOT EXISTS expense_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC NOT NULL,
  category VARCHAR NOT NULL, -- 'Fuel', 'Maintenance', 'Driver Payment', 'Accident', 'Insurance', 'Misc', 'Other'
  comment TEXT,
  status VARCHAR DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  requested_by VARCHAR DEFAULT 'staff',
  created_at TIMESTAMPTZ DEFAULT now(),
  approved_by VARCHAR DEFAULT NULL,
  approved_at TIMESTAMPTZ DEFAULT NULL
);

-- 4. Create audit logs table for unified request history
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id VARCHAR, -- Can reference ID of request from other tables
  request_type VARCHAR NOT NULL, -- 'bill_pass_create', 'bill_pass_update', 'bill_pass_duplicate', 'payment_acknowledgement', 'expense_report'
  submitted_by VARCHAR NOT NULL, -- e.g. 'staff'
  submitted_at TIMESTAMPTZ DEFAULT now(),
  status VARCHAR NOT NULL, -- 'Pending', 'Approved', 'Rejected', 'Edited', 'Deleted'
  action_by VARCHAR, -- 'admin', 'staff'
  action_at TIMESTAMPTZ,
  payload JSONB -- All submitted values
);

-- 5. Disable Row-Level Security (RLS) if you are accessing directly from client-side without auth
ALTER TABLE payment_acknowledgement_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE expense_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
