-- 1. Modify billdata table to support payment status tracking
ALTER TABLE billdata ADD COLUMN IF NOT EXISTS payment_status VARCHAR DEFAULT 'Not Received';
ALTER TABLE billdata ADD COLUMN IF NOT EXISTS payment_mode VARCHAR DEFAULT NULL;
ALTER TABLE billdata ADD COLUMN IF NOT EXISTS payment_comment TEXT DEFAULT NULL;

-- 2. Create payment acknowledgement requests table
CREATE TABLE IF NOT EXISTS payment_acknowledgement_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_no BIGINT NOT NULL,
  payment_mode VARCHAR NOT NULL,
  comment TEXT,
  status VARCHAR DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  requested_by VARCHAR DEFAULT 'staff',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Create expense reports table
CREATE TABLE IF NOT EXISTS expense_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount NUMERIC NOT NULL,
  category VARCHAR NOT NULL, -- 'Fuel', 'Maintenance', 'Driver Payment', 'Accident', 'Insurance', 'Misc', 'Other'
  comment TEXT,
  status VARCHAR DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  requested_by VARCHAR DEFAULT 'staff',
  created_at TIMESTAMPTZ DEFAULT now(),
  approved_by VARCHAR DEFAULT NULL,
  approved_at TIMESTAMPTZ DEFAULT NULL
);

-- 4. Create audit logs table for unified request history
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id VARCHAR, -- Can reference ID of request from other tables
  request_type VARCHAR NOT NULL, -- 'bill_pass_create', 'bill_pass_update', 'bill_pass_duplicate', 'payment_acknowledgement', 'expense_report'
  submitted_by VARCHAR NOT NULL, -- e.g. 'staff'
  submitted_at TIMESTAMPTZ DEFAULT now(),
  status VARCHAR NOT NULL, -- 'Pending', 'Approved', 'Rejected', 'Edited', 'Deleted'
  action_by VARCHAR, -- 'admin', 'staff'
  action_at TIMESTAMPTZ,
  payload JSONB -- All submitted values
);

-- 5. Disable Row-Level Security (RLS) if you are accessing directly from client-side without auth
ALTER TABLE payment_acknowledgement_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE expense_reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;

-- 5. Create keep-alive table and seed default row (to prevent Supabase free tier pause)
CREATE TABLE IF NOT EXISTS keepalive (
  id INT PRIMARY KEY,
  pinged_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO keepalive (id, pinged_at)
VALUES (1, now())
ON CONFLICT (id) DO NOTHING;

ALTER TABLE keepalive DISABLE ROW LEVEL SECURITY;

-- 6. Create cars registry table
CREATE TABLE IF NOT EXISTS cars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  registration_name VARCHAR NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Create drivers registry table
CREATE TABLE IF NOT EXISTS drivers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL,
  phone VARCHAR NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 8. Create car history log tables
CREATE TABLE IF NOT EXISTS car_service_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
  service_date DATE NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS car_km_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
  km_clocked NUMERIC NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS car_fuel_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
  liters NUMERIC NOT NULL,
  money NUMERIC NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS car_misc_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS car_insurance_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
  insurance_date DATE NOT NULL,
  insurance_from DATE NOT NULL,
  insurance_to DATE NOT NULL,
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS car_driver_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
  driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ DEFAULT now()
);

-- Disable RLS for all new tables for direct API access
ALTER TABLE cars DISABLE ROW LEVEL SECURITY;
ALTER TABLE drivers DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_service_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_km_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_fuel_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_misc_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_insurance_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE car_driver_history DISABLE ROW LEVEL SECURITY;

-- 9. Add profile columns to drivers table
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS dob DATE;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS aadhar_number VARCHAR;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS license_number VARCHAR;
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS date_of_joining DATE;

-- 10. Create unified fleet requests table for approval workflow
CREATE TABLE IF NOT EXISTS fleet_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_type VARCHAR NOT NULL, -- 'add_car', 'edit_car', 'add_driver', 'edit_driver', 'log_km', 'log_service', 'log_fuel', 'log_insurance', 'log_misc', 'assign_driver'
  payload JSONB NOT NULL,
  status VARCHAR DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  requested_by VARCHAR DEFAULT 'staff',
  created_at TIMESTAMPTZ DEFAULT now(),
  resolved_by VARCHAR DEFAULT NULL,
  resolved_at TIMESTAMPTZ DEFAULT NULL
);

ALTER TABLE fleet_requests DISABLE ROW LEVEL SECURITY;

-- 11. Add salary column to drivers table
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS salary NUMERIC DEFAULT 0;

-- 12. Create driver payments tracking table
CREATE TABLE IF NOT EXISTS driver_payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id BIGINT REFERENCES drivers(id) ON DELETE CASCADE,
  payment_date DATE NOT NULL,
  amount NUMERIC NOT NULL,
  type VARCHAR NOT NULL, -- 'salary_paid', 'deduction', 'advance'
  comment TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE driver_payments DISABLE ROW LEVEL SECURITY;
